const config = {
	size: 5,
	dict: [
		"drevorubač",
		"hnusné číslo",
		"zneužít",
		"Zuzka",
		"kolieska",
		"počuješ ma Tomáš?",
		"Hliněný",
		"čas na dôkaz",
		"Tony",
		"somarina",
		"umelý krok",
		"dcera",
		"stránky hliněné",
		"násilí",
		"hovadina",
		"přestávku?",
		"vyrušující ať jdou ven",
		"někdo spí",
		"rozmazanej / přesvícenej visualizér",
		"Veronika",
		"scheatovat",
		"nekonečná minuta",
		"Chuck Norris",
		"pozrem a vidim",
		"nepriatel",
		"vemte si ty papiery",
		"Adriana",
		"Lukáš",
		"finta",
	]
}
