const config = {
	size: 3,
	dict: [
		"\"egypťani\"",
		"astrid nestíhá",
		"libovolný org random pobíhá s vysílačkou v ruce",
		"potlesk",
		"v úloze je chyba",
		"rozbije se flaška",
		"vyhraje tým z jiného státu",
		"člověku na pódiu není rozumět ",
		"kdokoliv křičí na celou halu bingo",
		"dupkala v saku",
		"zbyde 14 tisíc sýrových mlsounů",
		"libovolný tým vzdal soutěž a jenom sedí u stolu",
		"účastníci si stěžují, že je merch moc drahý",
		"kdokoliv nadává na vzhled merche",
		"martin vaněk říká prázdná slova ",
		"je prezentace \"co je to FYKOS\"",
		"soutěžící se hádá o řešení s organizátorem ",
		"tým uvede výsledek alespoň o 20 řádů jinde",
		"registrace je chaotická",
		"neorganizátor má fyziklání triko",
		"organizátoři nevědí co mají dělat",
		"libovolný člověk má FYKOS merch",
		"libovolný člověk má výfuk merch",
		"libovolný člověk má chemiklání merch",
		"libovolný tým má matching trika",
		"týmy zdrhají ještě před vyhlášením",
		"příšerná angličtina",
		"organizátoři během opravování vytváří memes"
	]
}
