const config = {
	size: 5,
	dict: [
		"\"egypťani\"",
		"astrid nestíhá",
		"libovolný org random pobíhá s vysílačkou v ruce",
		"potlesk",
		"v úloze je chyba",
		"rozbije se flaška",
		"vyhraje tým z jiného státu",
		"člověku na pódiu není rozumět ",
		"kdokoliv křičí na celou halu bingo",
		"dupkala v saku",
		"zbyde 14 tisíc sýrových mlsounů",
		"libovolný tým vzdal soutěž a jenom sedí u stolu",
		"účastníci si stěžují, že je merch moc drahý",
		"kdokoliv nadává na vzhled merche",
		"martin vaněk říká prázdná slova ",
		"je prezentace \"co je to FYKOS\"",
		"soutěžící se hádá o řešení s organizátorem ",
		"tým uvede výsledek alespoň o 20 řádů jinde",
		"registrace je chaotická",
		"neorganizátor má fyziklání triko",
		"organizátoři nevědí co mají dělat",
		"libovolný člověk má FYKOS merch",
		"libovolný člověk má výfuk merch",
		"libovolný člověk má merch jiného semináře",
		"libovolný tým má matching trika",
		"týmy zdrhají ještě před vyhlášením",
		"příšerná angličtina",
		"organizátoři během opravování vytváří memes",
		"někdo něco vykřikne při přečtení prvních úloh",
		"stůl s bagetami bez lidí",
		"barikády z učebnic na stole",
		"dupkala říká vtipy a nikdo se nesměje",
		"agresivní propagace merche",
		"někdo běží k opravovatelům jak o život a pošlou ho zpátky",
		"fronty lidí co náhodně tipují na konci soutěže",
		"úloha o náhodném organizátorovi, co chápou jen organizátoři",
		"\"někdo něco ukradl, prosíme o navrácení\"",
		"tabulky z minulého století na stole",
		"fronta na záchodech",
		"tým na vyhlašované pozici není přítomný"
	]
}
