const config = {
	event: "tabor",
	size: 5,
	dict: [
		"Libovolný účastník běhá víc, než by musel",
		"\"Snídaně bude\"",
		"\"Svačina bude\"",
		"\"Oběd bude\"",
		"\"Večeře bude\"",
		"\"Jídlo bude\"",
		"Kuchyně nestíhá",
		"Je potřeba protáhnout hru",
		"Je potřeba zkrátit hru",
		"Účastníci už deset minut kladou otázky k pravidlům",
		"Libovolnému účastníkovi se nelíbí jídlo",
		"Jídlo je nezvykle tmavé",
		"Jídlo je nedovařené",
		"Jídlo je v nesprávné konzistenci",
		"Hra není připravená dvě hodiny před hrou",
		"Adam se snaží cokoliv zautomatizovat",
		"Nejede tiskárna",
		"Kdokoliv přetahuje přednášku o 10 minut",
		"Kdokoli dodělává hru v průběhu hry",
		"Kdokoli hledá zdravotníka",
		"Kdokoli chce z jídla vybrat hlavní ingredienci",
		"Do kuchyně přijde kdokoli v nejhektičtější čas",
		"Do kuchyně přijde org v pyžamu",
		"Kuchyně experimentuje s dochucováním jídla",
		"Kdokoli marně hledá políčko, který si může zaškrtnout",
		"Kdokoli pomlouvá fykos",
		"kdokoli si stěžuje na bingo",
		"kdokoli spotřeboval něco důležitýho",
		"kdokoli srovnává anežku s luborem",
		"kdokoli: \"to je černý záměrně?\"",
		"kdokoli vybízí k uvaření čínských polívek",
		"kdokoli vymýšlí, jak zachránit jídlo",
		"kdokoli zamění jména lubora, viktora a roberta",
		"kdokoli zapomněl nachystat svačinu",
		"kuchyně komukoliv vnucuje ovoce",
		"libovolná postel se propadne",
		"moment překvapení",
		"přehodilo se jídlo",
		"robert si čistí zuby",
		"\"to jsou lobotomové\"",
		"várnice je prázdná",
		"viktor má na sobě maskáče",
		"viktor něco vysvětluje se zdviženým ukazováčkem",
		"v jídle se vyskytuje ingredience, která tam zjevně nepatří",
		"v kuchyni je předmět, který tam očividně nepatří",
		"v libovolnou ranní hodinu se začíná připravovat oběd",
		"Martin má otázku",
		"kdokoli udělá meme na Egora",
		"v účastnickém pokoji je více orgů jak dětí",
		"jede 3D tiskárna"
	]
}
