const config = {
	event: "vykop",
	size: 5,
	dict: [
		"boří bleje po vodce ",
		"peší chce absinth",
		"peší pije absinth",
		"vojta bleje ",
		"lenka pije plzeň",
		"kdokoliv odchází pro kebab/do hladáče",
		"vylitý pití ",
		"Ok-B zpívá o půlnoci ",
		"někdo se ztratí ",
		"někdo agresivně kašle",
		"skřivan říká trapný vtipy",
		"rozbitá sklenička ",
		"boj o místa u stolu ",
		"libovolný člověk usnul ",
		"kdokoliv brečí ",
		"felda nestartuje",
		"mára chce řídit opilej ",
		"jsme v časovém skluzu",
		"béčko se tváří, že je lepší jak my ",
		"někdo skončil na zemi ",
		"hraje nothing else matters",
		"yasmi nebo potu pijou jednu skleničku už hodinu ",
		"husník zve všechny na potkání ",
		"hnojda dostal pěstí",
		"u stolu je někdo, kdo rozhodně nematuruje",
		"kdokoliv odchází před jednou hodinou ranní",
		"4.A náhodně přichází",
		"chalda je over it ",
		"venca za barem trpí ",
		"někdo něco ztratil ",
		"libovolný kostým se rozpadá",
		"někdo nafukuje svůj kostým",
		"mícovo auto nestartuje",
		"kdokoliv pije už třetího redbulla ",
		"hraje se prší",
		"kdokoliv řeší maturitu už 10 minut vkuse",
	]
}
